heyvanlar = [
    'Pinqvin',
    'Albatros',
    'Fırtınaquşu',
    'Kaçurka',
    'Qarabatdaq',
    'Vağlar',
    'Ördək',
    'Qaz',
    'Qağayı',
    'Şahin',
    'Berqut',
    'Qartal',
    'Qızılqaz',
    'Cüllüt',
    'Qutan',
    'Dovdaq',
    'Turac',
    'Leylək',
    'Tetra',
    'Qu-quşu',
    'Cürə',
    'Toyuq',
    'cücə',
    'sərçə',
    'qızılquş',
    'durna',
    'göyərçin',
    'qarqar',
    'qızılquş',
    'bayquş',
    'ağacdələn',
    'qutan',
    'şanapipik',
    'qaratoyuq',
    'sarıköynək',
    'alaçöhrə',
    'sığırçın',
    'qarğa',
    'qaranquş',
    'alabayquş',
    'flamingo',
    'bildirçin',
    'kəklik',
    'qirqovul',
    'qağayı',
    'keçisağan',
    "bülbül",
    'sağsağan',
    'sığırçın',
    'vələmirquşu',
    'kətanquşu',
    'quş',
    'Cənnətquşu',
    'Eşşəkarısı',
    'Balarısı',
    'Termit',
    'Arı',
    'Qara dul',
    'Tarakan',
    'Human mozalan',
    'Qırxayaq',
    'əqrəb',
    'qarışqa',
    'ağcaqanad',
    'milçək',
    'gənə',
    'qurd',
    'hörümçək',
    'cırcırama',
    'gənəcik',
    'güvə',
    'böcək',
    'birə',
    'bit',
    'tırtıl',
    'barama',
    'kəpənək',
    'qızılböcək',
    'Parabüzən',
    'birəcik',
    'ilbis',
    'Yarpaqyeyən',
    'ilan',
    'Gürzə',
    'Korilan',
    'təlxə',
    'Qonurilan',
    'Eyrenis',
    'Suilanı',
    'ox-ilan',
    'pişik ilanı',
    'Kərtənkələ',
    'Gekkon',
    'Kələz',
    'Girdəbaş',
    'Koramal',
    'Uzunayaq',
    'Sçink',
    'Çılpaqgöz',
    'Mabuya',
    'Kərtənkələcik',
    'ilanbaş',
    'bəbir',
    'camış'
    'canavar'
    'ceyran'
    'cüyür'
    'delfin'
    'dovşan'
    'dələ'
    'dəvə'
    'eşşək'
    'fil'
    'hus'
    'ilan'
    'ilanbalığı'
    'inək'
    'it'
    'kaftar'
    'keçi',
    'kirpi',
    'koala',
    'koramal',
    'köstəbək',
    'küçük',
    'kərgədan',
    'maral',
    'meymun',
    'panda',
    'pişik',
    'porsuq',
    'pələng',
    'qarışqayeyən',
    'qatır',
    'qaz',
    'qoyun',
    'qunduz',
    'qurbağa',
    'quzu',
    'sincab',
    'siçan',
    'siçovul',
    'suiti',
    'timsah',
    'tısbağa',
    'tülkü',
    'vaşaq',
    'yaquar',
    'yarasa',
    'yenot',
    'zağ',
    'zebr',
    'zürafə',
    'çaqqal',
    'çəpiş',
    'şir',
    'Tısbağa',
    'at',
    'ayı',
    'ağ ayı',
    'begemot',
    'bizon',
    'buzov',
    'heyvan',
    'həşərat',
    'balıq',
    'Qızılxallı balıq',
    'Xəşəm balıq',
    'Həşəm balıq',
    'Naxa balıq',
    'Qayabalığ',
    'Poru balıq',
    'Xul balıq',
    'Daban balıq',
    'Enlibaş balıq',
    'Altağız balıq',
    'Külmə balıq',
    'Şahmayı balıq',
    'Qızılbalıq',
    'Çapaq balıq',
    'Siyənək balıq',
    'Çəki balıq',
    'Şirbit balıq',
    'Sıf balıq',
    'Durna balıq',
    'Bölgə balıq',
    'Nərə balıq',
    'qurd',
    'kəpənək',
    'balina',
    'parabüzən',
    '10 nöqtəli adalia parabüzəni',
    '10 nöqtəli kalvia',
    '11-nöqtəli semiadalia parabüzəni',
    '12-nöqtəli vibidiya',
    '13 nöqtəli hippodamia parabüzəni',
    '14-ləkəli parabüzən',
    '14-nöqtəli propuleya parabüzəni',
    '22-Ləkəli tea parabüzəni',
    '4-Ləkəli ekzoxomus',
    '7 nöqtəli parabüzən',
    'Acar kərtənkələsi',
    'Açıq sarı dən sovkası',
    'Açıqalın şibyəyeyən',
    'Adadovşanı',
    'Adapazarı gürzəsi',
    'Addaks',
    'Adeli pinqvini',
    'Adenofor'
    'Ağacqurbağası',
    'Ağcaqanad',
    'Alabayquş',
    'Alasığırçın',
    'Apollon',
    'Arıyeyən',
    'Balıqcıl',
    'Bildirçin,'
    'Bizdimdik',
    'Bonazi tetrası',
    'Buqələmun',
    'Buruqboyun',
    'Canavar',
    'Caydaqcüllüt',
    'Çaqqal',
    'Çəki',
    'Çivdimdik',
    'Çökükburun',
    'Çöl kərtənkələsi',
    'Dəniz donuzu',
    'Dəniz iynəbalıqları',
    'Durnabalıq',
    'Düymədimdik',
    'Emu',
    'Ərsindimdik',
    'Gəlincik',
    'iquana',
    'İlanbalığı',
    'ilanboyun',
    'ilişgən',
    'Keçisağan',
    'Kenquru',
    'Kərgə',
    'Kərtənkələ',
    'Kirpi',
    'Köpgəröküz',
    'Köstəbək',
    'Külmə',
    'Kürəkburun',
    'Qalxanlı kazuar',
    'Qalxansifət',
    'Qaragöz qızılquş',
    'Qaraqaş',
    'Qaranaz'
    'Qarıldaq',
    'Qarqar',
    'Qarquşu',
    'Qaşqaldaq',
    'Qırqovul',
    'Qızılgöz',
    'Qızılqaz',
    'Qonurilan',
    'Qulaqlı bayquş',
    'Qurqur',
    'Quru qurbağası',
    'Mantispa',
    'Mavi zığ-zığ',
    'Meşəördəyi',
    'Muymul',
    'Mandu',
    'Pərttəgöz',
    'Pişik ilanı'
    'Sahil qaranquşu',
    'Sahildəyişən',
    'Sar',
    'Sərçə',
    'Sıf',
    'Sincab',
    'Sincabaoxşar',
    'Su keçisi',
    'Subirəsi',
    'Sufərəsi',
    'Suilanı',
    'Suiti',
    'Susüpürən',
    'Süngər',
    'Şəmayı',
    'Təqibçi',
    'Tənbəlcüllüt',
    'Tovuz quşu',
    'Triton',
    'Turac',
    'Tülkü',
    'Uzunqanad',
    'Vaşaq',
    'Yapalaq',
    'Yapalaqca',
    'Yaşıl balıqcıl',
    'Zığ-zığ',
    'Afrika bəbiri',
    'Afrika camışı',
    'Afrika çöl iti',
    'qartal'
]

